config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  root 'meetings#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord

     # This will guarantee set_duration is called before saving it to the database
  before_save :set_duration

  #def duration_add
   # duration = (end_date - start_date).to_i
  #end

  #def duration

   #self.duration = (end_date - start_date).to_i
    
    #end
    def daily_total_duration
      # Meeting.where("start_date >= ? AND end_date < ?", Time.now.beginning_of_day, Time.now.end_of_day).sum(:duration)
       #@meeting = Meeting.where("start_date >= ?", Time.now.beginning_of_week).sum(:duration)
    #  @meeting =  Meeting.where("start_date >= ? AND end_date < ?", Time.now.beginning_of_day, Time.now.end_of_day).sum(:duration)

      Meeting.where("start_date >= ? AND end_date  < ?", Time.now.beginning_of_day, Time.now.end_of_day).sum(:duration)
      end

      def weekly_total_duration
        #Meeting.where("start_date >= ? AND end_date < ?", Time.now.beginning_of_day, Time.now.end_of_day).sum(:duration)
        Meeting.where("start_date >= ?", Time.now.beginning_of_week).sum(:duration)
      end 
      
   # def all_day
    #  Meeting.where("created_at >= ? AND created_at < ?", Time.now.beginning_of_day, Time.now.end_of_day).sum(:duration)

    #end

    def set_duration
      self.duration = (end_date - start_date).to_i
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
    @meeting = Meeting.new
    @avg_review = Meeting.average(:duration)
   
    
  end
  

   
  # GET /meetings/1 or /meetings/1.json
  def show
  end

  
   

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_date, :end_date, :duration)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper

    def duration_display(meeting)

       duration = ActiveSupport::Duration.build(meeting.duration).parts 
        
        format('%02d hours and %02d minutes', (duration[:hours]||0), (duration[:minutes]||0), (duration[:seconds]||0))
        
        end
        
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Duration</th>
      <th>Duration Time</th>
      <th>Total hours per day</th>
      <th>Weekly hours per day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_date %></td>
        <td><%= meeting.end_date %></td>
        <td><%= meeting.duration %></td>
        <td><%= duration_display meeting  %></td>
        <td><%= meeting.daily_total_duration%></td>
        <td><%= meeting.weekly_total_duration%></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @meeting.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @meeting.end_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= duration_display @meeting %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>